apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: taxi-svc
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
status:
  loadBalancer: {}
