apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAqvW5jWa+XEQCAMwA1W5aYrYUTChaMKcMtn8Qr+C0TrOGL5yyirelhployThUILWgRq3kJZiKpUp41HUBVqa8mH2jU5EJ7cnTmjZEqyfhoJQSIgG8VjS1rFKEgfOa9lkB/YdXEiToJqlywMMmO4BTcZ2kQoCyrMiaHn9/vKZbgMUImMwbS7VZPMRIucxhlxMjrnLL5OwTOYNZm7lk0hIhNb/AcrKt49ooIfuzi5JWOatJiodFhLyW12lLGrx3B+t3C5XMC5Ldd7SgO4dKlV98rxhgfIz4c/AFvwmJBgP9J9GLmgYbvZuFrmmUaigp8GUlBkP6QlU5gtKE2L2vj+8KwW5zrvAZRPafBRet5GMn4RTvmlJKqZamZA2JAwcTaaC9YBmMSxoP2l8ABL+GwIhwg39kh0MWorOgdmk/nVy3yjF8C8YQccLxjWo8ZLtZZr6NNwc7eB4FRIi7oRfGbwe3xrt1qAz8TOr+7KfDAGNBRS5yUcyoDeuslNq/+XXAcbVShNQjFjasG9RWunPJtUwfjusxYpmdpijjuF4r+lOWSYGglvbXQ8XU3FPFdTodIF4InreTJg8otPZP1dzBo7PNhg8jCyWvhLjKMPKbGrR33DivA/vwFIL2inN6cW91ik+K0wSFo4kDni4bsmyOO8yWrTfIaPPzuyDZCGz9z8EDCnP5dw97MG+66F3aDU1M+m7LvfzlaorApaAxajUpSivn46QPHznyMDH0iPBuDOZmLi+z/QmZ9VqcHCtKEnFhrGC2+cZ6XXWoQu5l7AYI3p+sbVCyz4XmDR2olV8JhKTy3o2Llvmo5b9ge3bUWE4ElZQ1Md1EiDqkTuyRgIU79gOImlj5rxhAD/fAQmBOEXPaY5wc4n9Cnfg60NpTiLvYniv3DYmN2fQFCpooHUVkvc0hYy4m9tvgoJKoW1DbQgqDCdWQbtqdtb+O2JotXf0epdYc=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
