apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBcXkoUlNlNWHo/0QgeOq52mZvfOdl9Tis8VBjfX6z2Rw2wvwg1aLHWiPPcOn3DMgjtbQpw9vG1zY9X5Oh3rSfGB5GwbvUqkw4pYgyiGmVrmoO7FiIPlXDttlQ5frM0I5IcbioaucmoDn5rYGawrrDcS6neneI9g85/WQX62JFrbIrCVJ1CKIZEHZV13NmamstB9O7j+udqPQlKRNNMzrcw/1B4Y0XEJXRlXdR8NvZjvW8GuZXYzduCChk0fRfTtMOsH5KMkyDlR/rif4zI2DNi/POVJx8mGLXk+9SkrSqdg2LLrg2fRlHirmtFeF1+mf5peQI45dkMsQ4vR/f/Ilx/vUUzssrRUGFgCYGKCfGAwxXw3/PsvGOgq50Iw7nLn8DajgudmW9MzHgihA5mB8JqV2kdV7MwgNsjXs1J60uNjNhtH6ccYjir7rtCSXffGkLm9nL5Qu/SHud7AeoiXIUM7xw2DdwFl1wqjBvE+6FmUorYX7Epp16QwXedkwG2NTNvE0eAxiUvoCQsbpG8PO6Vz5Q06DcSfOMv6HeTGBeFQCxr6XbkX702LrjJmEjbpuKHvr0/EcygCRWEdb3+py3CS12pE21VyPpxQ3yv6GLIQPx3muAVH0IDenElILH4cPGA1r8Jnligi2i+9LyKNlGwfr6xGf02OcB1SJO62WMOQ4b2B5cEoR4ttT7vCrFtthAs4kRnEa5pLRXh/GSUSq0/UgExwUu8Un72g42FNA3KJfxB0OemFdq36wmOk5B1QpwdGKEpRD/pzVaJqCAjBVeXliKK5jF+DdCINbXG6Z7IpVzLHDU4EGOUneAYk714KqrpbTaB8G1uedFgtAXYgPQH5v6eULyW7+Vtjk9NAqEbdndYhtyn2kUGjU4lqDGc0cz3gsBg5l3TVnWuhxlyYub7G0c0y/0QMmKaVCTr71IlBxvEf9Ep09F2iv2VcbCfGMA=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
