apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    github-webhook-secret-taxi-svc: AgAq8NQyOJNwgrVx+Q+wwvtxulskIBHdNhBNe6gtE7OyEKUI+rX/Ft4Ypd/75GVXXWwnILVGkDnwVPn5Di/BjKC+MjIxUMDbcVywYwEVxt/uD52rH6ldlDl0QENHF8z3Hfv1JJriqJDynnGGL/LHmCD/LKUHPTGkds0zuUdo/5Kf4wKxVwqnsBPMZku5bcud1iztMS5xgmphKIQdwHDWU5G6oD4hoV3aNsMsgYizH2gU/Gin/EdBz97P6PJdrsTbMW0yPieVL5G5aQllg/F3AxgsgG6+O9KF0CvtrqIwUIPxDn4vGU8SIOoSPINtr0tBM2UsyfP1dheXGFQYxrRUCb3GP58lrFwava0bgYvpIo17WTnJ1w/KU0cILq3XCioLgXqTVzAaZn6TBrN1DXDOHd01Xj5HVg6vPlpxzpmXmSAHwnNzypSGj+GjTm1woxeDK7k2ygqaKFdmz9tNTAhxRjYcOAwedLcvTmVLRLbPOC64inZbA9M5fJ7cM6dgGhPvXYAklxKtmvQtPVT22hmQ1F7Bqbe8LG50oLswqXK3XNodNgvl6XG8VY5DWbfM+6WJGUf9gDMnZaNOSYhhRepJadFFFB+41W/MqyFkrLCyn5UNWlP4iSHADkj/0xv3dpEUqNko6DXKGLpv+j9Sps6Qy2JKVHCaBd1DRFrldu5qUt69sc6n8fouixStdhZyhlwMGPzaXIQ=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
