apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAH36vPhdcS4WvmfcFyqO9wU1DOKnd40tfmpGdPVGyFwEYpkhtgtByy88zf1AKj6+wOAiSn8t+uG8CpgxFXH3TI1F8Mg7ShI6N1UudutS6oeyBwqEd0KEdKcztyOdvPSHl+IxOLxSN1cdTKC53cvp877Hg/R9s2HgAmZanMIIzXJHG12ELLgvTpGpN/I1NKSnt7IWOxsKyl3yOxSFuo5ZSPXSylGlJgkBQ+lNkSJMba/JkczIRpB2pVQ+WWh2MVQDHy1Ft2TZif8g5NnfgmLMYFNFmw4gBHvSfDm0CEU1sGGX8h82PPprNyiSxaprEYEJxd/HUM7xa0fo19ZgtuiZ35CswBZnPdE3hcc+OnozqnJik8qr1o6hWW3Qp1931v4xz81t4JM4dxRjhpw56t87uzuVN0kc3izKJhsOHOyFwJgL++WZzJpjN7VrXlLEcZMuZBBIvlZqaFxBLsWvK7D+EIUd2vqyw5tkAd8WKI2sl/vj4lApx++9QGDxJxNeKyasHL/HyFF4bkIZ4BuktA/4cg5y1m/Crb+/6dJjryHbP5guaPinw8BrpCmca0ppZvGNtJSja1wUTuo4XjP2tmsSymV+SismXt+w/LeM8up/QTe+lv0422HcEB7tMNN/Wt+UoynAjsZNrD+bptDrEicWHjM8RH2V0TQ4zbwb5iDCjr/ncSSxwODC/Jf+3DmZOP2T7NAxc=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
