apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBoclEKvFlNpVZeUl1Xv2Fs9uU63RgO5YQxtDkaWZrZ5gzN2HEJd2P0mlOtce+pZGaEmXBEVv8pD8zNrOpDmANhANmX6LbH+fKaMH+Lf77Nn7hhUcFwC2hEaSDnB5qnUITdXFELr/CSLG32CXEADlP1UXzZxKEBEiHTLEm6CLuKqDEbyU0ZcvyY4U6r/lRa2KXGdl9WQAS9uvisOVZ4//ge8a6SNt+OOdyAyM+oi3XFWKJ7Qo1ekl2jak8+dqMlH9fqeHj243FPUi3PDyFCNoVW0jLyBDiyP0NMtuNMgaDmZyA0AaEaHyUMLKQEO3b2PqWpjukGkMiQ7+MicmoxkT9/hiq1Ak1aIXx6XwchuDVAB/HY8ZS/5GpU58zhY4OlBcvSCxtA3G5wmo4W65q/FgrL47oYHBcC+e9yTVNEDSFXwxENprtlQ5n4YvIgqqHG6fOKL8jmUirdsSUEIv4rRiEXgp7l77YJCpKwtVMI5kq1xcVACUFORNC1IrENeOCrem7zOAYrXwYY0qOlq/DfKpz7IekiLTPFcObPNdzBnXD3IK+9PvHZui9qq9DEyDQ35ZH7opakHmoWb3iLM83iupN83eNDHQHo4jzYEGcZk3pNYR9X2Sxts5wO6quH53CsyboVHoJ9g/bcBcvo2yuDL9h+O6j9AH8BYx9Iw/7PSnlBtX3U3PIVNV5cDW07jjDOfndqbmw=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
