apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: cicd
spec:
  serviceAccountName: ""
  triggers:
  - bindings:
    - name: github-pr-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'pull_request') && body.action ==
          'opened' || body.action == 'synchronize') && body.pull_request.head.repo.full_name
          == 'chetan-rns/taxi'
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: github-webhook-secret-taxi-svc
    name: app-ci-build-from-pr-taxi-svc
    template:
      name: app-ci-template
  - bindings:
    - name: github-pr-binding
    interceptors:
    - cel:
        filter: (header.match('X-GitHub-Event', 'pull_request') && body.action ==
          'opened' || body.action == 'synchronize') && body.pull_request.head.repo.full_name
          == 'chetan-rns/gitops-bootstrap'
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    name: ci-dryrun-from-pr
    template:
      name: app-ci-template
status:
  configuration:
    generatedName: ""
